package ui;

import estadojuego.EstadoJuego;
import main.Juego;
import multijugador.Usuario;

/**
 *
 * @author Gabriel
 */
public class PanelIniciado extends javax.swing.JPanel {

    private Juego juego;
    private Usuario usuario;

    /**
     * Creates new form PanelIniciado
     *
     * @param juego
     */
    public PanelIniciado(Juego juego) {
        initComponents();
        this.juego = juego;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        Bienvenido.setText("Bienvenido, " + usuario.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bienvenido = new javax.swing.JLabel();
        IniPartida = new javax.swing.JButton();
        UnirPartida = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1040, 672));
        setMinimumSize(new java.awt.Dimension(1040, 672));
        setPreferredSize(new java.awt.Dimension(1040, 672));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bienvenido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Bienvenido.setText("jLabel1");
        add(Bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 320, 70));

        IniPartida.setText("Iniciar Partida");
        IniPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniPartidaActionPerformed(evt);
            }
        });
        add(IniPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 130, 30));

        UnirPartida.setText("Unirse a Partida");
        UnirPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnirPartidaActionPerformed(evt);
            }
        });
        add(UnirPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 130, 30));

        jButton3.setText("Estadísticas");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 130, 30));

        jButton4.setText("Ayuda");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 130, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void IniPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniPartidaActionPerformed
        juego.iniciarServidor();
        juego.iniciarCliente();
        juego.getPanelPartida().setAnfitrion(true);
        juego.cambiarPanel("Partida");
        juego.getJugando().iniciarJugando(usuario);
        EstadoJuego.estado = EstadoJuego.JUGANDO;
    }//GEN-LAST:event_IniPartidaActionPerformed

    private void UnirPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnirPartidaActionPerformed
        juego.iniciarCliente();
        juego.getPanelPartida().setAnfitrion(false);
        juego.cambiarPanel("Partida");
        juego.getJugando().iniciarJugando(usuario);
        EstadoJuego.estado = EstadoJuego.JUGANDO;
    }//GEN-LAST:event_UnirPartidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JButton IniPartida;
    private javax.swing.JButton UnirPartida;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
