package ui;

import estadojuego.Menu;

/**
 *
 * @author Gabriel
 */
public class PanelInicio extends javax.swing.JPanel {
    
    private Menu menu;

    /**
     * Creates new form Inicio
     */
    public PanelInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BotonIniRegistro = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MARIO BROS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 260, 70));

        BotonIniRegistro.setText("Registrarse");
        BotonIniRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniRegistroActionPerformed(evt);
            }
        });
        add(BotonIniRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 100, -1));

        jButton2.setText("Iniciar Sesion");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BotonIniRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonIniRegistroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIniRegistro;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
