package ui;

import estadojuego.Menu;
import java.awt.Dimension;
import main.Juego;
import static main.Juego.JUEGO_ALTO;
import static main.Juego.JUEGO_ANCHO;

/**
 *
 * @author Gabriel
 */
public class PanelInicio extends javax.swing.JPanel {

    private Menu menu;
    private Juego juego;

    /**
     * Creates new form Inicio
     *
     * @param juego
     */
    public PanelInicio(Juego juego) {
        initComponents();
        centrarComponentes();
        // Dar tamaño al panel
        Dimension dimension = new Dimension(JUEGO_ANCHO, JUEGO_ALTO);
        setMinimumSize(dimension);
        setMaximumSize(dimension);
        setPreferredSize(dimension);
        revalidate();
        repaint();
        this.juego = juego;
    }

    private void centrarComponentes() {
        Titulo.setLocation(JUEGO_ANCHO - Titulo.getWidth() / 2, Titulo.getY());
        BotonIniRegistro.setLocation(JUEGO_ANCHO - BotonIniRegistro.getWidth() / 2, BotonIniRegistro.getY());
        BotonIniSesion.setLocation(JUEGO_ANCHO - BotonIniSesion.getWidth() / 2, BotonIniSesion.getY());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        BotonIniRegistro = new javax.swing.JButton();
        BotonIniSesion = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1040, 672));
        setMinimumSize(new java.awt.Dimension(1040, 672));
        setPreferredSize(new java.awt.Dimension(1040, 672));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("MARIO BROS");
        add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 260, 70));

        BotonIniRegistro.setText("Registrarse");
        BotonIniRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniRegistroActionPerformed(evt);
            }
        });
        add(BotonIniRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 100, 30));

        BotonIniSesion.setText("Iniciar Sesion");
        BotonIniSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniSesionActionPerformed(evt);
            }
        });
        add(BotonIniSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BotonIniRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniRegistroActionPerformed
        juego.cambiarPanel("Registro");
    }//GEN-LAST:event_BotonIniRegistroActionPerformed

    private void BotonIniSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniSesionActionPerformed
        juego.cambiarPanel("Sesion");
    }//GEN-LAST:event_BotonIniSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIniRegistro;
    private javax.swing.JButton BotonIniSesion;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
