package ui;

import archivos.ArchivoUsuarios;
import java.io.IOException;
import java.util.ArrayList;
import main.Juego;
import multijugador.Usuario;

/**
 *
 * @author Gabriel
 */
public class PanelSesion extends javax.swing.JPanel {

    private Juego juego;

    /**
     * Creates new form PanelSesion
     */
    public PanelSesion(Juego juego) {
        initComponents();
        Salir.setIcon(
                new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Salir.png")).getImage().getScaledInstance(200, 40, java.awt.Image.SCALE_SMOOTH))
        );
        SesionBoton.setIcon(
                new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Iniciar Sesion.png")).getImage().getScaledInstance(200, 40, java.awt.Image.SCALE_SMOOTH))
        );
        Fondo.setIcon(
                new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/FondoMenu.png")).getImage().getScaledInstance(1040, 558, java.awt.Image.SCALE_SMOOTH))
        );
        this.juego = juego;
        Error.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LoginField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SesionBoton = new javax.swing.JButton();
        Error = new javax.swing.JLabel();
        ContraField = new javax.swing.JPasswordField();
        Salir = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1040, 558));
        setMinimumSize(new java.awt.Dimension(1040, 558));
        setPreferredSize(new java.awt.Dimension(1040, 558));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Iniciar Sesión");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 210, 40));

        jLabel2.setText("Login");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));
        add(LoginField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 260, 30));

        jLabel3.setText("Contraseña");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        SesionBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Iniciar Sesion.png"))); // NOI18N
        SesionBoton.setContentAreaFilled(false);
        SesionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SesionBotonActionPerformed(evt);
            }
        });
        add(SesionBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 200, 40));

        Error.setForeground(new java.awt.Color(255, 0, 51));
        Error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Error.setText("jLabel4");
        add(Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 260, -1));
        add(ContraField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 260, 30));

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Salir.png"))); // NOI18N
        Salir.setContentAreaFilled(false);
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 200, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/FondoMenu.png"))); // NOI18N
        add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void SesionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SesionBotonActionPerformed
        Error.setVisible(false);
        String login = LoginField.getText().trim();
        String contraseña = new String(ContraField.getPassword()).trim();
        if (login.length() == 0 || contraseña.length() == 0) {
            Error.setText("No puede dejar campos vacios");
            Error.setVisible(true);
            return;
        }

        ArchivoUsuarios archivo = new ArchivoUsuarios();
        try {
            archivo.abrirArchivoLectura();
            ArrayList<Usuario> usuarios = archivo.leerUsuarios();
            for (Usuario u : usuarios) {
                if (u.getLogin().equals(login) && u.getContraseña().equals(contraseña)) {
                    // Consiguió al usuario
                    juego.getPanelIniciado().setUsuario(u);
                    juego.cambiarPanel("Iniciado");
                    return;
                }
            }
            Error.setText("Login o contraseña incorrecta");
            Error.setVisible(true);
        } catch (IOException e) {
            Error.setText("Error abriendo archivo");
            Error.setVisible(true);
        } catch (ClassNotFoundException e) {
            Error.setText("Error leyendo archivo");
            Error.setVisible(true);
        } finally {
            try {
                archivo.cerrarArchivo();
            } catch (IOException e) {
                System.out.println("Error cerrando archivo");
            }
        }
    }//GEN-LAST:event_SesionBotonActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        juego.cambiarPanel("Inicio");
        juego.getPanelInicio().requestFocusInWindow();
    }//GEN-LAST:event_SalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ContraField;
    private javax.swing.JLabel Error;
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField LoginField;
    private javax.swing.JButton Salir;
    private javax.swing.JButton SesionBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
